#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum {
    TD_DOWN_DEL,
    TD_UP_PSCR,
};

void dance_up_scrot(tap_dance_state_t *state, void *user_data) {
    switch (state->count) {
        case 1:
            tap_code(KC_UP);
            break;
        case 2:
            register_code(KC_LGUI);
            register_code(KC_LSFT);
            register_code(KC_PSCR);
            clear_keyboard();
            break;
    }
}

tap_dance_action_t tap_dance_actions[] = {
    [TD_DOWN_DEL] = ACTION_TAP_DANCE_DOUBLE(KC_DOWN, KC_DEL),
    [TD_UP_PSCR]  = ACTION_TAP_DANCE_FN(dance_up_scrot),
};

bool get_hold_on_other_key_press(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QK_LAYER_TAP ... QK_LAYER_TAP_MAX:
            return true;
        default:
            return false;
    }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_4x6_5(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TAB, KC_Q, KC_W, KC_D, KC_F, KC_K, KC_J, KC_U, KC_R, KC_L, KC_SCLN, RALT_T(KC_BSLS), RCTL_T(KC_ESC), KC_A, KC_S, KC_E, KC_T, KC_G, KC_Y, KC_N, KC_I, KC_O, KC_H, LCTL_T(KC_QUOT), KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_P, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, LT(2, KC_LEFT), KC_SPC, KC_BSPC, KC_LGUI, KC_ENT, LT(1, KC_RGHT), TD(TD_DOWN_DEL), RCS(KC_C), RCS(KC_V), TD(TD_UP_PSCR)),
                                                              [1] = LAYOUT_split_4x6_5(KC_NO, KC_NO, KC_EQL, KC_PLUS, KC_TILD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, CW_TOGG, KC_EXLM, KC_AT, KC_HASH, KC_LBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_MINS, KC_DLR, KC_PERC, KC_CIRC, KC_LPRN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_UNDS, KC_AMPR, KC_ASTR, KC_GRV, KC_LCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_UP, KC_DOWN, KC_NO),
                                                              [2] = LAYOUT_split_4x6_5(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RBRC, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RPRN, KC_4, KC_5, KC_6, KC_0, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RCBR, KC_1, KC_2, KC_3, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LCTL(KC_END), KC_UP, KC_DOWN, KC_NO)};
